#!/usr/bin/env node
/**
 * AUMARA Director — GitHub-native agent.
 * Reads the actual Auto-Prepare-Merge conclusion. A green badge with a
 * failing lint step is a hold, not a go.
 */

const TOKEN = process.env.GITHUB_TOKEN;
const REPO = process.env.GITHUB_REPOSITORY;
const PR = process.env.PR_NUMBER || "";
const HEAD_SHA = process.env.HEAD_SHA || process.env.GITHUB_SHA || "";
const PREPARE_CONCLUSION = (process.env.PREPARE_CONCLUSION || "").toLowerCase();

if (!TOKEN || !REPO) {
  console.error("GITHUB_TOKEN and GITHUB_REPOSITORY are required");
  process.exit(1);
}

const [owner, repo] = REPO.split("/");

async function gh(path, { method = "GET", body } = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`${method} ${path} ${res.status} ${text}`);
  return text ? JSON.parse(text) : null;
}

async function prepareConclusion() {
  if (PREPARE_CONCLUSION) return PREPARE_CONCLUSION;
  if (!HEAD_SHA) return "unknown";
  const data = await gh(
    `/repos/${owner}/${repo}/actions/workflows/auto-prepare-merge.yml/runs?head_sha=${HEAD_SHA}&per_page=5`,
  );
  const run = (data.workflow_runs || []).find((r) => r.status === "completed");
  return (run?.conclusion || "unknown").toLowerCase();
}

function decision({ lockTouched, prepare }) {
  if (prepare !== "success") {
    return {
      verdict: "HOLD",
      text: `Auto-Prepare-Merge conclusion is **${prepare}**. Green means typecheck AND lint both passed. Do not merge.`,
    };
  }
  if (lockTouched) {
    return {
      verdict: "HOLD",
      text: "Lock or terrain changed. Re-run the L2 smoke suite before merge.",
    };
  }
  return {
    verdict: "GO",
    text: "Auto-Prepare-Merge is a real success (typecheck + lint). Lock untouched. Ready for review.",
  };
}

function buildReport({ pulls, files, prepare, verdict }) {
  const lines = [
    "## AUMARA Director",
    "",
    `Repository: **${owner}/${repo}**`,
    `Open PRs: **${pulls.length}**`,
    `Auto-Prepare-Merge: **${prepare}**`,
    "",
  ];

  if (PR) {
    lines.push(`### PR #${PR}`);
    lines.push(`Changed files: **${files.length}**`);
    for (const f of files.slice(0, 24)) {
      lines.push(`- \`${f.filename}\` (+${f.additions}/-${f.deletions})`);
    }
    lines.push("");
    lines.push(`### Decision: ${verdict.verdict}`);
    lines.push(verdict.text);
  } else if (pulls.length === 0) {
    lines.push("PR queue is empty. Pipeline is standing by for the next slice.");
  }

  for (const p of pulls) {
    lines.push(`- [#${p.number}](${p.html_url}) ${p.title} (${p.draft ? "draft" : p.state})`);
  }

  lines.push("");
  lines.push("_Generated by `agent/director.mjs` — AUMARA / EL CID standard._");
  return lines.join("\n");
}

async function main() {
  const pulls = await gh(`/repos/${owner}/${repo}/pulls?state=open&per_page=20`);
  const files = PR
    ? await gh(`/repos/${owner}/${repo}/pulls/${PR}/files?per_page=100`)
    : [];
  const prepare = await prepareConclusion();
  const lockTouched = files.some(
    (f) => f.filename === "AUMARA_TWIN_LOCK.json" || f.filename.startsWith("twin/"),
  );
  const verdict = decision({ lockTouched, prepare });
  const report = buildReport({ pulls, files, prepare, verdict });
  console.log(report);
  if (PR) {
    await gh(`/repos/${owner}/${repo}/issues/${PR}/comments`, {
      method: "POST",
      body: { body: report },
    });
    console.log(`Commented on PR #${PR}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
