#!/usr/bin/env node
/**
 * AUMARA Director — GitHub-native agent.
 * Runs in Actions with GITHUB_TOKEN. No Copilot SDK required.
 */

const TOKEN = process.env.GITHUB_TOKEN;
const REPO = process.env.GITHUB_REPOSITORY;
const PR = process.env.PR_NUMBER || "";

if (!TOKEN || !REPO) {
  console.error("GITHUB_TOKEN and GITHUB_REPOSITORY are required");
  process.exit(1);
}

const [owner, repo] = REPO.split("/");

async function gh(path, { method = "GET", body } = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`${method} ${path} ${res.status} ${text}`);
  return text ? JSON.parse(text) : null;
}

function buildReport({ pulls, files }) {
  const lines = [
    "## AUMARA Director",
    "",
    `Repository: **${owner}/${repo}**`,
    `Open PRs: **${pulls.length}**`,
    "",
  ];

  if (PR) {
    lines.push(`### PR #${PR}`);
    lines.push(`Changed files: **${files.length}**`);
    for (const f of files.slice(0, 24)) {
      lines.push(`- \`${f.filename}\` (+${f.additions}/-${f.deletions})`);
    }
    lines.push("");
    const lockTouched = files.some(
      (f) => f.filename === "AUMARA_TWIN_LOCK.json" || f.filename.startsWith("twin/"),
    );
    lines.push("### Decision");
    lines.push(
      lockTouched
        ? "Lock or terrain changed. Re-run the L2 smoke suite before merge."
        : "Lock untouched. After Auto-Prepare-Merge is green, this PR is ready for review.",
    );
  } else if (pulls.length === 0) {
    lines.push("PR queue is empty. Pipeline is standing by for the next slice.");
  }

  for (const p of pulls) {
    lines.push(`- [#${p.number}](${p.html_url}) ${p.title} (${p.draft ? "draft" : p.state})`);
  }

  lines.push("");
  lines.push("_Generated by `agent/director.mjs` — AUMARA / EL CID standard._");
  return lines.join("\n");
}

async function main() {
  const pulls = await gh(`/repos/${owner}/${repo}/pulls?state=open&per_page=20`);
  const files = PR
    ? await gh(`/repos/${owner}/${repo}/pulls/${PR}/files?per_page=100`)
    : [];
  const report = buildReport({ pulls, files });
  console.log(report);
  if (PR) {
    await gh(`/repos/${owner}/${repo}/issues/${PR}/comments`, {
      method: "POST",
      body: { body: report },
    });
    console.log(`Commented on PR #${PR}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
